dist: trusty
language: node_js
node_js:
- 10
before_install:
- sudo apt-get update
install:
- sudo apt-get install fakeroot
- sudo apt-get install rpm
- npm install
- cd ./installers/linux
- npm install
- cd ../../
script:
- npm run build:app
- cd ./installers/linux
- node ./build.js
- cd ../../
after_success: 
- chmod +x ./travis.sh
- ./travis.sh -t upload-linux-package
- ls
- ls ./dist
- ls ./dist/electron
- ls ./installers/linux/dist
- ls ./dist/electron/PrivateMail-linux-x64


