dist: trusty
language: node_js
node_js:
- 10
install:
- npm install
- cd ./installers/linux
- npm install
- cd ../../
- ls
script:
- npm run build:app
- node ./installers/linux/build.js
after_success: 
- ls
- ls ./installers/linux/dist