dist: trusty
language: node_js
node_js:
- 10
install:
- npm install
- cd ./installers/linux
- npm install
- cd ../../
- ls
script:
- npm run build:app
- cd ./installers/linux
- node ./build.js
- cd ../../
after_success: 
- ls
- ls ./dist
- ls ./installers/linux/dist
- ls ./dist/electron/PrivateMail-linux-x64


