dist: trusty
language: node_js
node_js:
- 10
before_install:
- sudo apt-get update
install:
- sudo apt-get install fakeroot
- sudo apt-get install rpm
- npm install
- cd ./installers/linux
- npm install
- cd ../../
script:
- npm run build:app
- cd ./installers/linux
- node ./build.js
- cd ../../
after_success: 
- chmod +x ./travis.sh
- ./travis.sh -t upload-deb-package
- ./travis.sh -t upload-rpm-package
